# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b09b2c753445e6c61b59599cad19f2ad4e48dace058ad524f1e683e35e8e4f0a1b1935ab1e25bcd450020eb070d98e1c3fbf7f9c32f23f6a8d20e684955dc044

test:
  secret_key_base: 82af8549a35b2a2f07b4e567296224bc5829820ee312e77a531f54b46f79f1fa916ec1186fa063cef42b3f270a599a5c91fbfc922f525b696cc5dd4de03476f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
